# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0072_companyrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='alumni_reps',
            field=models.ManyToManyField(related_name='Alumni_Representatives', to='theme.CompanyRep'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='number_of_representatives',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='reps',
            field=models.ManyToManyField(related_name='Representatives', to='theme.CompanyRep'),
        ),
    ]
