# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0102_auto_20160612_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_uid',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
